### ISSUE TITLE
Needs local postinstall script

### ISSUE THREAD

**Issue by coolaj86** [janniks/basetag#18]
It seems that any time you run `npm install` it will clean out unrecognized files and directories, such as `node_modules/$`, but it doesn't re-run the postinstall scripts.

I think this should create a postinstall key in the local `package.json` to run `npx basetag` (for which a script would need to be provided), and print a message letting the user know to do so if a different `postinstall` already exists.

**Comment by janniks** [comment]
I'll do some investigating - that is a real problem 😕

`postinstall` sounds like an option. I might start setting up that `bin` architecture now then...

**Comment by janniks** [comment]
You are right. I will remodel basetags approach during #17
