### ISSUE TITLE
when using in docker, link points to local fs

### ISSUE THREAD

**Issue by maikelmclauflin** [janniks/basetag#23]
full branch is here: https://github.com/brave-intl/bat-ratios/pull/69
```
➜  bat-ratios git:(add-basetag) ✗ docker-compose -f docker-compose.yml run -v $(pwd):/usr/src/app -w /usr/src/app ratios-history ls -la node_modules/$
Creating bat-ratios_ratios-history_run ... done
lrwxrwxr-x    1 root     root            56 Jan 27 05:48 node_modules/$ -> /Users/michaelmclaughlin/Documents/brave-intl/bat-ratios
```
symlink should instead be pointing to local filesystem's relative path? perhaps i am just dockering wrong

**Comment by janniks** [comment]
We now support relative links 🙌 those should work even inside the docker image.
_If not it's always possible to setup basetag inside docker..._
