### ISSUE TITLE
Link relative rather than absolute?

### ISSUE THREAD

**Issue by coolaj86** [janniks/basetag#24]
I have a build and deploy process in which the build happens in a temp directory and then deploys to a different directory to be run.

When this happens there's an error because `$` points to `/tmp/random-name` rather than `../`.

**Comment by coolaj86** [comment]
Looks like this should do the trick on Mac and Linux:

```js
diff --git a/bin/basetag.js b/bin/basetag.js
index 252a1ab..f112b86 100755
--- a/bin/basetag.js
+++ b/bin/basetag.js
@@ -44,7 +44,7 @@ try {
     throw new Error(`- File already exists: ${baseLink}`);
   }

-  fs.symlinkSync(base, baseLink, 'junction');
+  fs.symlinkSync(base, '..', 'junction');

   log(`- Created $ symlink to ${base}\n`);
 } catch (error) {
```

**Comment by janniks** [comment]
Very very good idea! Someone else had similar problems — I honestly did not now relative symlinks exist, I'll also test this out tomorrow...

**Comment by janniks** [comment]
Thanks for the idea! 💡
